### PR TITLE
KULRICE-14162 : jquery ui upgrade to 1.11.2

### PR DESCRIPTION
**Pull request by cwade179**

### CODE REVIEW

**Comment by jruch** [comment]
Can one of the admins verify this patch?

**Comment by cniesen** [comment]
ok to test

**Comment by jruch** [comment]
Can one of the admins verify this patch?

**Comment by cniesen** [comment]
ok to test

**Comment by cniesen** [comment]
looks good

**Comment by bsmith83** [comment]
Should be fine

**Pull request merged**
