### PR TITLE
KULRICE-14175	- Unit test failure JpaMetadataProviderTest

### PR DESCRIPTION
**Pull request by shahess**

### CODE REVIEW

**Comment by shahess** [comment]
retest this please

**Comment by cniesen** [comment]
I've been looking at the code and still don't feel comfortable in what it is doing. The whole `getRelationshipByLastAttributeInRelationship` method is confusing to me.  Would take quite some time to familiarize myself with the code and the use case to make concrete suggestions.

From the little I know though there are some imperfections:
*  `createAttributeRelationshipList` method has some deep nesting of if statements.
* the three lists being passed to `createAttributeRelationshipList` method that are updated in the method.  Would be nice if the method could just return the attributeRelationships. An alternative might be to use a different verb for what the method is doing instead of create (populate/build).

I'm still very tempted to accept the pull request as it seems to fix the issue.

**Comment by kellerj** [comment]
I'll take a look at it tomorrow too.  Shannon and I talked about it last week and I remember why it was doing what it did.  The issue is that an assumption about an internal of either EclipseLink or Java changed with the upgrade to Java 8 and/or EclipseLink.

**Comment by shahess** [comment]
Thanks Jonathan for taking a look, I could use some suggestions on how to improve the code.   Claus, I'll take a look and see if I can make the createAttributeRelationshipList better myself as well.   

Just for anyone reviewing, what I did was get the primary keys that we are wanting to retain the order of (referencedEntityPkFields), and then I just made sure that they are added to attributeRelationships in that order.   When I did my testing, I verified that they are now getting added to attributeRelationships in the same order as referencedEntityPkFields  (created by calling getPrimaryKeyAttributeNames, which returns the primary keys in order).

**Comment by shahess** [comment]
retest this please

**Comment by kellerj** [comment]
Shannon, I left some comments/questions on the commit.  Do those get emailed to you?

**Comment by shahess** [comment]
I just committed a change that makes the createAttributeRelationshipList method less complicated.  I realized I didn't need one of the else sections.

**Comment by shahess** [comment]
Jonathan, I just saw that email, I take a look at your comments now.

**Comment by kellerj** [comment]
Huh.  Did you amend your commit?  GitHub seems to have deleted my comments.

**Comment by shahess** [comment]
I have your comments in an email... did you just add them as a comment on this pull request?   I'm having such a hard time adjusting to Git!  

Regarding your comments, I see what you mean.  I will make the changes you suggested, that seems like a much cleaner way to do things.

**Comment by shahess** [comment]
Comments from Jonathan - 

It seems that the way to run this would be to use the referencedEntityPkFields object (which will be in the correct order) and iterate over that. Then, for each one, find the matching entry in the relationshipMapping object and build as before.

I'd have to look at the available API methods, but it seems that some combination of relationshipMapping.getForeignKeyFields() and relationshipMapping.getTargetToSourceKeyFields() might be able to pull the information.

**Comment by kellerj** [comment]
No.  I went into the commit and was leaving the comments on particular lines.  I re-added the main one since I still had most of it on my clipboard.  Good to know that it sends out an email immediately to the committer though.

**Comment by shahess** [comment]
Yes, I also think its strange that me updating the code causes your comments to go away.  It's too bad that is the case.

**Comment by kellerj** [comment]
It's why I asked if you amended the commit.  When you do that, the old
commit is effectively thrown away (still there, but not in the branch
history).  My comments were attached to that exact commit - not the pull
request itself.

--
Jonathan

**Comment by shahess** [comment]
I'm made the coded changes and the code is much better.  It no longer calls any additional methods and all tests are passing locally.    Claus and Jonathan, can you take another look at the changes?

**Comment by cniesen** [comment]
retest this please

**Comment by kellerj** [comment]
:thumbsup:

**Comment by cniesen** [comment]
retest this please

**Comment by cniesen** [comment]
retest this please

**Comment by cniesen** [comment]
Looks good.

**Pull request merged**
