### PR TITLE
KULRICE-14248

### PR DESCRIPTION
**Pull request by mcnewk**

### CODE REVIEW

**Comment by cniesen** [comment]
ready to test

**Comment by cniesen** [comment]
ok to test

**Comment by shahess** [comment]
I've been talking to Kurt about this and asked him it he could remove the change to the .gitignore file.  Unless others think that is a change we should bring in?

**Comment by cniesen** [comment]
Either is fine with me in regards to the .gitignore change.  If it makes is easier for mac users we can leave it in.

**Comment by mcnewk** [comment]
closing this out.  I will create a new one without the .gitingore change.

**Pull request closed without merging**
