### PR TITLE
[KULRICE-14171] Fix for EditRuleBkMrkAft failures

### PR DESCRIPTION
**Pull request by bsmith83**

### CODE REVIEW

**Comment by bsmith83** [comment]
It is unknown if this will fix the ci test, but it seems to be working 100% of the time against env2 since I added these few lines

**Comment by cniesen** [comment]
The pre-merger build failed for an unrelated and known test failure.

**Comment by cniesen** [comment]
Worth a try.  Looks good.

**Comment by sonamuthu** [comment]
looks good

**Pull request merged**
