### PR TITLE
KULRICE-13136: Performance improvement on populateRoleMembers

### PR DESCRIPTION
**Pull request by jwbennet**
Added a new helper which find the RoleMemberBo objects for a given
principal and role then updated populateRoleMembers to use it instead of
fetching all roles for the user and doing manual population of the list.

### CODE REVIEW

**Comment by jruch** [comment]
Can one of the admins verify this patch?

**Comment by jruch** [comment]
Can one of the admins verify this patch?

**Comment by cniesen** [comment]
ok to test

**Comment by bsmith83** [comment]
Looks fine but I dont know exactly what its doing.  Also I noticed there are 2 commits under commits.

**Comment by jwbennet** [comment]
It looks like since we applied two different contributions to master they are both getting pulled in with this pull request.  We've started making feature branches for the other contributions which should help prevent that from happening again, but if we can handle both of those issues in one pull request this time that may be easiest for us.

**Comment by shahess** [comment]
Hi James,

I'm going to be verifying this patch.

Thanks,
Shannon

**Comment by shahess** [comment]
I tested the KULRICE-13136 portion of this change and it looks good to me.  I'm going to put more details on the JIRA regarding how I tested.   We don't have any large roles for me to have noticed a performance improvement, but the code works as expected.  Do you happen to have any data on how the performance was improved by the change?

**Comment by jwbennet** [comment]
Hello Shannon,

It has been a few months, but at IU the person maintenance document wouldn't even route if someone was in one of our biggest roles (and some people are in more than one).  The routing process would take so long that it would eventually stop trying after 30-45 minutes of routing attempts.  With the new setup it routes in a couple of seconds so it is significantly faster.

Also, KULRICE-14035 was also brought in with this pull request due to us misunderstanding how the pull request process works between two projects.  Did you want to verify that as well?

Thanks,
James

**Comment by shahess** [comment]
James, 

Thanks for the info regarding the person maintenance document at IU, that's a great improvement.  

I reviewed the code for KULRICE-14035 and it looks good to me.  I've merged this pull request into the code base as well so I believe that both KULRICE-14035 and KULRICE-14035 can be closed. 

Thanks,
Shannon

**Pull request merged**
