### PR TITLE
KULRICE-14147 - Remove libary samples from jscalendar-1.0

### PR DESCRIPTION
**Pull request by bsmith83**

### CODE REVIEW

**Comment by cniesen** [comment]
Duplicate of pull request https://github.com/kuali/rice/pull/40 of master branch

**Comment by cniesen** [comment]
@bsmith83 Two file deletes are missing in this pr:
* rice-middleware/web/src/main/webapp/ken/scripts/jscalendar-1.0/doc/html/field-button.jpg
* rice-middleware/web/src/main/webapp/ken/scripts/jscalendar-1.0/doc/reference.pdf

**Comment by cniesen** [comment]
retest this please

**Comment by bsmith83** [comment]
File deletions fixed

**Pull request merged**
