### PR TITLE
[KULRICE-14148] Removed comments and fixed small problems with test

### PR DESCRIPTION
**Pull request by bsmith83**

### CODE REVIEW

**Comment by jruch** [comment]
Can one of the admins verify this patch?

**Comment by jruch** [comment]
Can one of the admins verify this patch?

**Comment by cniesen** [comment]
ok to test

**Comment by cniesen** [comment]
looks good

**Comment by shahess** [comment]
Looks good, I pulled in the changes and and ran DemoTravelAccountLookUpAft on firefox to verify that there wouldn't be any issues.

**Pull request merged**
