### PR TITLE
KULRICE-14131 : JDK8 changes

### PR DESCRIPTION
**Pull request by cwade179**

### CODE REVIEW

**Comment by cniesen** [comment]
Let's hold off on this merger until the ci integration tests pass.  Especially so we know if issues happened because of the Spring 4 upgrade or the Java 8 upgrade.

**Comment by cwade179** [comment]
Ok, good idea

**Comment by cniesen** [comment]
add to whitelist

**Comment by cniesen** [comment]
ok to test

**Comment by cniesen** [comment]
looks good

**Comment by shahess** [comment]
looks good to me as well

**Pull request merged**
