### PR TITLE
KULRICE-14100 kimIdentityDelegateService bean definition in KIMLdapSprin...

### PR DESCRIPTION
**Pull request by sonamuthu**
...gBeans.xml is broken

### CODE REVIEW

**Comment by coreypedersen** [comment]
Sona: Your comments on the Jira say you needed a sample-app pom change to go with this

**Comment by sonamuthu** [comment]
Corey, those were needed to test that the server started up properly with the ldap integration. By default it is not turned on.

**Comment by sonamuthu** [comment]
Should I close this pull request since this was linked to the old forked rice?

**Comment by sonamuthu** [comment]
Yes it does.

**Pull request closed without merging**
