### PR TITLE
Deletion of unnecessary library files

### PR DESCRIPTION
**Pull request by bsmith83**

### CODE REVIEW

**Comment by jruch** [comment]
Can one of the admins verify this patch?

**Comment by jruch** [comment]
Can one of the admins verify this patch?

**Comment by cniesen** [comment]
looks good

FYI these files are generated via maven import and don't need to be included in the rice source

**Comment by cniesen** [comment]
ok to test

**Comment by jruch** [comment]
not much to review.  A bunch of file removals.  Looks good.

**Pull request merged**
